#!/usr/bin/env python3
"""
Claude Code stop hook: reads session transcript from stdin, writes a summary
entry to ~/projects/Mhai2/DEVLOG.md using the Anthropic API.
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path

DEVLOG = Path.home() / "projects" / "Mhai2" / "DEVLOG.md"
MODEL = "claude-haiku-4-5"


def main():
    raw = sys.stdin.read().strip()
    if not raw:
        return

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return

    # Extract messages from the transcript
    messages = data.get("messages", [])
    if not messages:
        return

    # Build a compact transcript for summarisation (cap at ~8K chars)
    lines = []
    for m in messages:
        role = m.get("role", "")
        content = m.get("content", "")
        if isinstance(content, list):
            parts = []
            for block in content:
                if isinstance(block, dict):
                    if block.get("type") == "text":
                        parts.append(block.get("text", ""))
                    elif block.get("type") == "tool_use":
                        parts.append(f"[tool: {block.get('name', '')}]")
                    elif block.get("type") == "tool_result":
                        parts.append("[tool_result]")
            content = " ".join(parts)
        if content:
            lines.append(f"{role.upper()}: {str(content)[:400]}")
    transcript = "\n".join(lines)[:8000]

    if not transcript.strip():
        return

    try:
        import anthropic
        client = anthropic.Anthropic()
        response = client.messages.create(
            model=MODEL,
            max_tokens=512,
            system=(
                "You summarise Claude Code development sessions for a dev log. "
                "Output a brief markdown entry (3-8 bullet points) covering: "
                "what was built or discovered, what worked, any workflows validated, "
                "any tools or approaches tried. Be factual and concrete. "
                "Focus on novel discoveries and validated workflows — skip routine chat. "
                "Output ONLY the bullet points, no preamble."
            ),
            messages=[{"role": "user", "content": f"Transcript:\n{transcript}"}],
        )
        summary = response.content[0].text.strip()
    except Exception as e:
        summary = f"_(summary unavailable: {e})_"

    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    entry = f"\n## {date_str}\n\n{summary}\n"

    DEVLOG.parent.mkdir(parents=True, exist_ok=True)
    if not DEVLOG.exists():
        DEVLOG.write_text("# Mhai2 Development Log\n\nAuto-generated by Claude Code stop hook.\n")

    with DEVLOG.open("a") as f:
        f.write(entry)


if __name__ == "__main__":
    main()
